"""empty message

Revision ID: 6a8fc4fbb2c9
Revises: f1277284864b
Create Date: 2022-08-24 01:03:38.468231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8fc4fbb2c9'
down_revision = 'f1277284864b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
